### ISSUE TITLE
deployOpenshift.sh unable to find etc/ansible/ansible.cfg

### ISSUE THREAD

**Issue by edmacabebe** [Microsoft/openshift-container-platform#100]
Deployment failed. Correlation ID: 7a334184-682a-48d4-bec6-041a67552f9c. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=2\\n[stdout]\\nThu May 17 10:25:46 UTC 2018  - Starting Script\\nConfiguring SSH ControlPath to use shorter path name\\n\\n[stderr]\\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\\n                                 Dload  Upload   Total   Spent    Left  Speed\\n\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r100    13  100    13    0     0   1013      0 --:--:-- --:--:-- --:--:--  1083\\nsed: can't read /etc/ansible/ansible.cfg: No such file or directory\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

A snip in deployOpenshift.sh
echo "Configuring SSH ControlPath to use shorter path name"

sed -i -e "s/^# control_path = %(directory)s\/%%h-%%r/control_path = %(directory)s\/%%h-%%r/" /etc/ansible/ansible.cfg
sed -i -e "s/^#host_key_checking = False/host_key_checking = False/" /etc/ansible/ansible.cfg
sed -i -e "s/^#pty=False/pty=False/" /etc/ansible/ansible.cfg

Shouldn't all prep scripts for nodes invoke
yum -y install ansible   ??

**Comment by haroldwongms** [comment]
Ansible is installed on the Bastion.  Which branch are you using?

**Comment by haroldwongms** [comment]
Closing due to lack of response.
