### ISSUE TITLE
v3.9.30 deployment fails because 2 lines are not added to the inventory

### ISSUE THREAD

**Issue by antoniogallegosaez** [Microsoft/openshift-container-platform#105]
Please add two new lines into the inventory in DeployOpenShift.sh, so the installation can be completed successfully. This is the related solution: https://access.redhat.com/solutions/3480921. The lines are:

oreg_url=registry.access.redhat.com/openshift3/ose-${component}:${version}
openshift_examples_modify_imagestreams=true

**Comment by vincepower** [comment]
Thanks, I'm testing this and will submit a pull request as soon as the test succeeds.

**Comment by haroldwongms** [comment]
This is fixed in PR#108, 109 and 110
