### ISSUE TITLE
Setup of Container Native Storage

### ISSUE THREAD

**Issue by mglantz** [Microsoft/openshift-container-platform#13]
Hey there,

What do you think about a pull request which adds support for running OpenShift CNS (Container Native Storage)?

More info here: https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.3/html/container-native_storage_for_openshift_container_platform/

TL;DR: Tight integration with Gluster based software defined storage. Provisioning, setup, configuration of persistent storage for pods happens automatically. Communication goes via a heketi pod to gluster nodes which also can be run as pods on specific nodes where you have your dedicated disk devices. Gluster then takes responsibility of replicating the data on the local disk across the different CNS nodes.

The initial configuration I have in mind is re-using the infra nodes to deploy Gluster and Heketi pods on - as it doesn't require much additional work. It's also a supported configuration of CNS.

**Comment by mglantz** [comment]
Note, I have CNS working in a fork here: https://github.com/mglantz/ocp36-azure-cns

**Comment by haroldwongms** [comment]
CNS is now an option with 3.9 cluster.  I am closing.
