### ISSUE TITLE
osImageType now required by Azure?

### ISSUE THREAD

**Issue by bkugler-xv** [Microsoft/openshift-container-platform#132]
I get errors when deploying a 3.9 cluster in Azure when it tries to spin up the nodes.  It is complaining that the osImageType is missing.  My deployments were working back in June.

"details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidTemplate\",\r\n    \"message\": \"Deployment template validation failed: 'The value for the template parameter 'osImageType' at line '41' and column '18' is not provided. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.\"\r\n  }\r\n}"
    },

I see that the master / 3.10 templates have this field.  Was this a change in Azure, breaking the 3.9 deployments?  Or am I missing something else?  I tried to find anything referencing this requirement in Azure, but I'm not having any luck.

**Comment by haroldwongms** [comment]
@bkugler-xv,

Are you using the release-3.9 branch?  I implemented the osImageType in 3.10 but did not backport to 3.9.  Even for 3.10, I set the default value to 'defaultgallery" so if you don't define this parameter, it will just default ot the on-demand RHEL gallery image.

**Comment by bkugler-xv** [comment]
I will have to recreate, it has been a few weeks.  I'm almost certain I was
using the 3.9 branch, thus the question about if this was a change on the
Azure side that needed backporting.

**Comment by haroldwongms** [comment]
@bkugler-xv Let me know what you find.  Thank you.

**Comment by haroldwongms** [comment]
no response so assuming no longer an issue.
