### ISSUE TITLE
Marketplace OS Image - BYOS - cannot be used

### ISSUE THREAD

**Issue by Zuldajri** [Microsoft/openshift-container-platform#135]
Hello Guys,

I'm raising an issue regarding the marketplaceOSImage.
So I don't pay double for the RHEL subscriptions, I'm trying to use the marketplace image that is BYOS.

I entered the appropriate values for 'publisher', 'offer', 'sku', 'version' of the marketplace offer. (they got updated, we can now chose between rhel-raw75, rhel-lvm74 and rhel-lvm75).

The issue I have is that this template is private. I tried to accept the marketplace terms, but it's not working :) !

b'{"error":{"code":"MarketplacePurchaseEligibilityFailed","message":"Marketplace purchase eligibilty check returned errors. See inner errors for details. ","details":[{"code":"BadRequest","message":"Offer with PublisherId: redhat, OfferId: rhel-byos cannot be purchased due to validation errors. See details for more information.[{\\"Legal terms have not been accepted for this item on this subscription. To accept legal terms using PowerShell, please use Get-AzureRmMarketplaceTerms and Set-AzureRmMarketplaceTerms API(https://go.microsoft.com/fwlink/?linkid=862451) or deploy via the Azure portal to accept the terms\\":\\"StoreApi\\"},{\\"**Offer with PublisherId: redhat, OfferId: rhel-byos, PlanId: rhel-raw75 is private and can not be purchased by subscritpionId**: *******************************\\":\\"StoreApi\\"}]"}]}}'
msrest.exceptions : Marketplace purchase eligibilty check returned errors. See inner errors for details.

If you have an idea, that would be wonderful!!

Thank you so much,

Best regards,
William

**Comment by BorisB2015** [comment]
William (@Zuldajri), 

Please use http://aka.ms/rhel-byos-preview - this is an entry point for Red Hat Cloud Access program for the RHEL BYOS images you currently see in the gallery.

**Comment by Zuldajri** [comment]
Thanks for the feedbacks guys.

Nice to know there is a process to use your Red Hat subscriptions (with Cloud Access) or through the Red Hat CCSP.

Any idea when it would go GA?

Thank you so much,
William
