### ISSUE TITLE
VM has reported a failure when processing extension 'deployOpenShift' on Azure Stack.

### ISSUE THREAD

**Issue by arheukels** [Microsoft/openshift-container-platform#137]
Please can somebody help, the installation keeps on failing with the message "

"VM has reported a failure when processing extension 'deployOpenShift'. Error message: Enable failed: failed to execute command: command terminated with exit status=4"

For now i am using a RHEL trial license with 10 hosts and OpenShift.
masters = 3
Infra = 2
Node =1
CNS =true (3 hosts)
Bastion = 1

If somebody can help or if more information is needed, please let me know.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: Enable failed: failed to execute command: command terminated with exit status=4\\n[stdout]\\nK [Evaluate oo_etcd_hosts_to_backup] ****************************************\\nok: [localhost] => (item=tmw-d-mstr-0)\\nok: [localhost] => (item=tmw-d-mstr-1)\\nok: [localhost] => (item=tmw-d-mstr-2)\\n\\nTASK [Evaluate oo_nodes_to_config] *********************************************\\nok: [localhost] => (item=tmw-d-mstr-0)\\nok: [localhost] => (item=tmw-d-mstr-1)\\nok: [localhost] => (item=tmw-d-mstr-2)\\nok: [localhost] => (item=tmw-d-inf-0)\\nok: [localhost] => (item=tmw-d-inf-1)\\nok: [localhost] => (item=tmw-d-node-0)\\nok: [localhost] => (item=tmw-d-cns-0)\\nok: [localhost] => (item=tmw-d-cns-1)\\nok: [localhost] => (item=tmw-d-cns-2)\\n\\nTASK [Add master to oo_nodes_to_config] ****************************************\\nskipping: [localhost] => (item=tmw-d-mstr-0) \\nskipping: [localhost] => (item=tmw-d-mstr-1) \\nskipping: [localhost] => (item=tmw-d-mstr-2) \\n\\nTASK [Evaluate oo_lb_to_config] ************************************************\\n\\nTASK [Evaluate oo_nfs_to_config] ***********************************************\\n\\nTASK [Evaluate oo_glusterfs_to_config] *****************************************\\nok: [localhost] => (item=tmw-d-cns-0)\\nok: [localhost] => (item=tmw-d-cns-1)\\nok: [localhost] => (item=tmw-d-cns-2)\\n\\nTASK [Evaluate oo_etcd_to_migrate] *********************************************\\nok: [localhost] => (item=tmw-d-mstr-0)\\nok: [localhost] => (item=tmw-d-mstr-1)\\nok: [localhost] => (item=tmw-d-mstr-2)\\n\\nPLAY [Install and configure NetworkManager] ************************************\\n\\nTASK [Gathering Facts] *********************************************************\\nfatal: [tmw-d-inf-0]: UNREACHABLE! => {\\\"changed\\\": false, \\\"msg\\\": \\\"Failed to connect to the host via ssh: ssh: Could not resolve hostname tmw-d-inf-0: Name or service not known\\\\r\\\\n\\\", \\\"unreachable\\\": true}\\nfatal: [tmw-d-cns-1]: UNREACHABLE! => {\\\"changed\\\": false, \\\"msg\\\": \\\"Failed to connect to the host via ssh: ssh: Could not resolve hostname tmw-d-cns-1: Name or service not known\\\\r\\\\n\\\", \\\"unreachable\\\": true}\\nok: [tmw-d-cns-0]\\nok: [tmw-d-cns-2]\\nok: [tmw-d-mstr-0]\\nok: [tmw-d-mstr-2]\\nok: [tmw-d-inf-1]\\nok: [tmw-d-node-0]\\nok: [tmw-d-mstr-1]\\n\\nTASK [install NetworkManager] **************************************************\\nok: [tmw-d-inf-1]\\nok: [tmw-d-mstr-0]\\nok: [tmw-d-mstr-2]\\nok: [tmw-d-cns-2]\\nok: [tmw-d-mstr-1]\\nok: [tmw-d-node-0]\\nok: [tmw-d-cns-0]\\n\\nTASK [configure NetworkManager] ************************************************\\nchanged: [tmw-d-inf-1] => (item=USE_PEERDNS)\\nchanged: [tmw-d-mstr-2] => (item=USE_PEERDNS)\\nchanged: [tmw-d-node-0] => (item=USE_PEERDNS)\\nchanged: [tmw-d-cns-2] => (item=USE_PEERDNS)\\nchanged: [tmw-d-mstr-0] => (item=USE_PEERDNS)\\nchanged: [tmw-d-mstr-1] => (item=USE_PEERDNS)\\nchanged: [tmw-d-cns-0] => (item=USE_PEERDNS)\\nok: [tmw-d-mstr-2] => (item=NM_CONTROLLED)\\nok: [tmw-d-inf-1] => (item=NM_CONTROLLED)\\nok: [tmw-d-node-0] => (item=NM_CONTROLLED)\\nok: [tmw-d-mstr-0] => (item=NM_CONTROLLED)\\nok: [tmw-d-cns-2] => (item=NM_CONTROLLED)\\nok: [tmw-d-cns-0] => (item=NM_CONTROLLED)\\nok: [tmw-d-mstr-1] => (item=NM_CONTROLLED)\\n\\nTASK [enable and start NetworkManager] *****************************************\\nok: [tmw-d-mstr-0]\\nok: [tmw-d-node-0]\\nok: [tmw-d-cns-0]\\nok: [tmw-d-cns-2]\\nok: [tmw-d-mstr-2]\\nok: [tmw-d-inf-1]\\nok: [tmw-d-mstr-1]\\n\\nPLAY RECAP *********************************************************************\\nlocalhost : ok=12 changed=0 unreachable=0 failed=0 \\ntmw-d-cns-0 : ok=4 changed=1 unreachable=0 failed=0 \\ntmw-d-cns-1 : ok=0 changed=0 unreachable=1 failed=0 \\ntmw-d-cns-2 : ok=4 changed=1 unreachable=0 failed=0 \\ntmw-d-inf-0 : ok=0 changed=0 unreachable=1 failed=0 \\ntmw-d-inf-1 : ok=4 changed=1 unreachable=0 failed=0 \\ntmw-d-mstr-0 : ok=4 changed=1 unreachable=0 failed=0 \\ntmw-d-mstr-1 : ok=4 changed=1 unreachable=0 failed=0 \\ntmw-d-mstr-2 : ok=4 changed=1 unreachable=0 failed=0 \\ntmw-d-node-0 : ok=4 changed=1 unreachable=0 failed=0 \\n\\n\\n[stderr]\\n# tmw-d-cns-0:22 SSH-2.0-OpenSSH_7.4\\n# tmw-d-cns-0:22 SSH-2.0-OpenSSH_7.4\\n# tmw-d-cns-0:22 SSH-2.0-OpenSSH_7.4\\nWarning: Permanently added the ECDSA host key for IP address '10.1.0.6' to the list of known hosts.\\r\\ngetaddrinfo tmw-d-cns-1: Name or service not known\\r\\ngetaddrinfo tmw-d-cns-1: Name or service not known\\r\\ngetaddrinfo tmw-d-cns-1: Name or service not known\\r\\nssh: Could not resolve hostname tmw-d-cns-1: Name or service not known\\r\\n# tmw-d-cns-2:22 SSH-2.0-OpenSSH_7.4\\n# tmw-d-cns-2:22 SSH-2.0-OpenSSH_7.4\\n# tmw-d-cns-2:22 SSH-2.0-OpenSSH_7.4\\nWarning: Permanently added the ECDSA host key for IP address '10.1.0.7' to the list of known hosts.\\r\\n [WARNING]: Could not create retry file '/usr/share/ansible/openshift-\\nansible/playbooks/openshift-node/network_manager.retry'. [Errno 13]\\nPermission denied: u'/usr/share/ansible/openshift-ansible/playbooks/openshift-\\nnode/network_manager.retry'\\n\"\r\n }\r\n ]\r\n }\r\n}"}]}

Kind Regards,
Arie Heukels

**Comment by arheukels** [comment]
Changed the Disk size and VM size and now i  get the exit code 2.
These are the parameters i use for the installation.

- VM-Size Standard_DS2_v2

- openshiftClusterPrefix = tmw-d

- masterInstanceCount = 3

- infraInstanceCount = 2

- nodeInstanceCount = 1

- dataDiskSize = 128GB

- enableMetrics = false

- enableLogging = true

- enableCNS = true

- rhsmUsernameOrOrgId = using RedHat trial license for now

----error-----

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"VMExtensionProvisioningError\\\",\\r\\n \\\"message\\\": \\\"VM has reported a failure when processing extension 'deployOpenShift'. Error message: Enable failed: failed to execute command: command terminated with exit status=2\\\\n[stdout]\\\\norage_glusterfs : Delete deploy resources] *******************\\\\nchanged: [tmw-d-mstr-0] => (item={u'kind': u'template,route,service,jobs,dc,secret', u'selector': u'deploy-heketi'})\\\\nchanged: [tmw-d-mstr-0] => (item={u'kind': u'svc', u'name': u'heketi-storage-endpoints'})\\\\nok: [tmw-d-mstr-0] => (item={u'kind': u'secret', u'name': u'heketi-storage-topology-secret'})\\\\n\\\\nTASK [openshift_storage_glusterfs : Generate heketi endpoints] *****************\\\\nchanged: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Generate heketi service] *******************\\\\nchanged: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Create heketi endpoints] *******************\\\\nchanged: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Create heketi service] *********************\\\\nchanged: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Copy heketi template] **********************\\\\nchanged: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Create heketi template] ********************\\\\nchanged: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Deploy heketi pod] *************************\\\\nchanged: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Wait for heketi pod] ***********************\\\\nFAILED - RETRYING: Wait for heketi pod (30 retries left).\\\\nFAILED - RETRYING: Wait for heketi pod (29 retries left).\\\\nFAILED - RETRYING: Wait for heketi pod (28 retries left).\\\\nFAILED - RETRYING: Wait for heketi pod (27 retries left).\\\\nFAILED - RETRYING: Wait for heketi pod (26 retries left).\\\\nFAILED - RETRYING: Wait for heketi pod (25 retries left).\\\\nFAILED - RETRYING: Wait for heketi pod (24 retries left).\\\\nFAILED - RETRYING: Wait for heketi pod (23 retries left).\\\\nok: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Set heketi-cli command] ********************\\\\nok: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Verify heketi service] *********************\\\\nok: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Check if gluster-s3 can't be deployed] *****\\\\nok: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Create heketi secret] **********************\\\\nchanged: [tmw-d-mstr-0]\\\\n\\\\nTASK [openshift_storage_glusterfs : Generate GlusterFS StorageClass file] ******\\\\nfatal: [tmw-d-mstr-0]: FAILED! => {\\\\\\\"changed\\\\\\\": false, \\\\\\\"failed\\\\\\\": true, \\\\\\\"msg\\\\\\\": \\\\\\\"AnsibleUndefinedVariable: 'glusterfs_heketi_route' is undefined\\\\\\\"}\\\\n\\\\nPLAY RECAP *********************************************************************\\\\nlocalhost : ok=13 changed=0 unreachable=0 failed=0 \\\\ntmw-d-cns-0 : ok=146 changed=59 unreachable=0 failed=0 \\\\ntmw-d-cns-1 : ok=146 changed=59 unreachable=0 failed=0 \\\\ntmw-d-cns-2 : ok=146 changed=59 unreachable=0 failed=0 \\\\ntmw-d-inf-0 : ok=143 changed=57 unreachable=0 failed=0 \\\\ntmw-d-inf-1 : ok=143 changed=57 unreachable=0 failed=0 \\\\ntmw-d-mstr-0 : ok=521 changed=215 unreachable=0 failed=1 \\\\ntmw-d-mstr-1 : ok=348 changed=142 unreachable=0 failed=0 \\\\ntmw-d-mstr-2 : ok=348 changed=142 unreachable=0 failed=0 \\\\ntmw-d-node-0 : ok=143 changed=57 unreachable=0 failed=0 \\\\n\\\\n\\\\nINSTALLER STATUS ***************************************************************\\\\nInitialization : Complete (0:00:39)\\\\n\\\\t[DEPRECATION WARNING]: The following are deprecated variables and will be no longer be used in the next minor release. Please update your inventory accordingly.\\\\n\\\\topenshift_hosted_metrics_public_url\\\\nHealth Check : Complete (0:01:19)\\\\netcd Install : Complete (0:02:51)\\\\nMaster Install : Complete (0:05:56)\\\\nMaster Additional Install : Complete (0:05:33)\\\\nNode Install : Complete (0:11:18)\\\\nGlusterFS Install : In Progress (0:06:58)\\\\n\\\\tThis phase can be restarted by running: playbooks/openshift-glusterfs/config.yml\\\\n\\\\n\\\\n\\\\nFailure summary:\\\\n\\\\n\\\\n 1. Hosts: tmw-d-mstr-0\\\\n Play: Configure GlusterFS\\\\n Task: Generate GlusterFS StorageClass file\\\\n Message: AnsibleUndefinedVariable: 'glusterfs_heketi_route' is undefined\\\\n\\\\n[stderr]\\\\n# tmw-d-cns-0:22 SSH-2.0-OpenSSH_7.4\\\\n# tmw-d-cns-0:22 SSH-2.0-OpenSSH_7.4\\\\n# tmw-d-cns-0:22 SSH-2.0-OpenSSH_7.4\\\\nWarning: Permanently added the ECDSA host key for IP address '10.1.0.6' to the list of known hosts.\\\\r\\\\n# tmw-d-cns-1:22 SSH-2.0-OpenSSH_7.4\\\\n# tmw-d-cns-1:22 SSH-2.0-OpenSSH_7.4\\\\n# tmw-d-cns-1:22 SSH-2.0-OpenSSH_7.4\\\\nWarning: Permanently added the ECDSA host key for IP address '10.1.0.7' to the list of known hosts.\\\\r\\\\n# tmw-d-cns-2:22 SSH-2.0-OpenSSH_7.4\\\\n# tmw-d-cns-2:22 SSH-2.0-OpenSSH_7.4\\\\n# tmw-d-cns-2:22 SSH-2.0-OpenSSH_7.4\\\\nWarning: Permanently added the ECDSA host key for IP address '10.1.0.5' to the list of known hosts.\\\\r\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_hosts_containerized_managed_true\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config\\\\n [WARNING]: Consider using yum, dnf or zypper module rather than running rpm\\\\n [WARNING]: Consider using file module with mode rather than running chmod\\\\n [WARNING]: Consider using unarchive module rather than running tar\\\\n [WARNING]: Consider using get_url or uri module rather than running curl\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_containerized_master_nodes\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_nodes_use_flannel\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_nodes_use_calico\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_nodes_use_contiv\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nodes_use_kuryr\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nodes_use_nuage\\\\n [WARNING]: Could not match supplied host pattern, ignoring: glusterfs_registry\\\\n [WARNING]: Could not create retry file '/usr/share/ansible/openshift-\\\\nansible/playbooks/deploy_cluster.retry'. [Errno 13] Permission denied:\\\\nu'/usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.retry'\\\\n\\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by haroldwongms** [comment]
@arheukels,

As @BorisB2015 mentioned, the stdout and stderr files (deployment logs) will provide more helpful detail than the fragments from the ARM provider.  

Also, Infra nodes of size DS2_v2 will most likely experience issues if logging is enabled.

**Comment by arheukels** [comment]
@haroldwongms @BorisB2015 It is all new for me, thank you for the support.

When i try to login to the Bastion node by using Putty with the username and password in the parameters to collect the logs it failed. 

Access denied
Using keyboard-interactive authentication.

**Comment by haroldwongms** [comment]
@arheukels You log into the bastion host using the private key that matches the public key you used for deployment.  That was the same key you stored in the Key Vault.  

The password you specified is for log in to OpenShift itself once the cluster is up and running.

**Comment by arheukels** [comment]
@haroldwongms  Thank you

I still have to do some more research, for now i find a lot of heteki errors in "stdout" log

TASK [openshift_storage_glusterfs : Wait for heketi pod] ***********************
FAILED - RETRYING: Wait for heketi pod (30 retries left).
FAILED - RETRYING: Wait for heketi pod (29 retries left).
FAILED - RETRYING: Wait for heketi pod (28 retries left).
FAILED - RETRYING: Wait for heketi pod (27 retries left).
FAILED - RETRYING: Wait for heketi pod (26 retries left).
FAILED - RETRYING: Wait for heketi pod (25 retries left).
FAILED - RETRYING: Wait for heketi pod (24 retries left).
FAILED - RETRYING: Wait for heketi pod (23 retries left).
ok: [tmw-d-mstr-0]

Failure summary:

  1. Hosts:    tmw-d-mstr-0
     Play:     Configure GlusterFS
     Task:     Generate GlusterFS StorageClass file
     Message:  AnsibleUndefinedVariable: 'glusterfs_heketi_route' is undefined

**Comment by haroldwongms** [comment]
@arheukels, you will see tasks that have failures and retries because the playbook task is waiting for the pod to start or for something to happen.  That is why they put retry logic into the task.  In the case with gluster, you can see there were a set of retries but ultimately, it came back with ok: [tmw-d-mstr-0], so that pod did start.  The stderr log will have a bunch of warnings but these are not fatal errors.  Is it possible for you to email me the stdout file?  Harold.wong@microsoft.com

Thanks.

**Comment by arheukels** [comment]
@haroldwongms Going to grab the logs and will mail them.

Really appreciate the support.

**Comment by haroldwongms** [comment]
Give me a few days to look into this.

**Comment by arheukels** [comment]
@haroldwongms Did a new deployment with "AZ CLI" and still get the same error 

"Configuring SSH ControlPath to use shorter path name\\n\\n[stderr]\\nsed: can't read /etc/ansible/ansible.cfg"

Connected from Bastion to the master nodes and checked if i can find the "ansible.cfg" but it is not on the  master nodes. Where can i find this file "ansible.cfg" and can i add it manually?

Will send you also the latest logfiles

**Comment by haroldwongms** [comment]
ansible.cfg is on the bastion.  Also, per my email, please verify the pool id as you are getting an error that the OpenShift Repo is not available.

**Comment by haroldwongms** [comment]
@arheukels Any update?

**Comment by arheukels** [comment]
@haroldwongms small update

In the output from the installation i noticed  "\\\": \\\"Unable to connect to the server: dial tcp 185.242.244.58:443: i/o timeout\\\\n\\\", \\\"stdout\\\": 

Tried to do a wget https://185.242.244.58:443 --no-check-certificate from the Bastion node after the failed installation and it is successful. Why is it showing a time out at the installation then.

**Comment by arheukels** [comment]
Was missing a dns forwarder on the internal DNS to Azure stack for cloudapp.com that is needed for the load balancer.
More information https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-dns
