### ISSUE TITLE
fix samples.json with proper github URL

### ISSUE THREAD

**Issue by marcosgm** [Microsoft/openshift-container-platform#15]
See https://github.com/Microsoft/openshift-container-platform/blob/master/azuredeploy.parameters.json
and https://github.com/Microsoft/openshift-container-platform/blob/master/azuredeploy.parameters.sample.json
It contains
                "_artifactsLocation": {
                        "value": "https://raw.githubusercontent.com/haroldwongms/openshift-containerplatform/master"
                },

In that case, the deployment will fail complaining about diagStorageAccount and Role not being valid inputs in the template.

Even though both files are just samples, for the sake of first time users, please update the github URL to point to this repo ("https://raw.githubusercontent.com/Microsoft/openshift-container-platform/master") or delete the variable altogether. Otherwise, the error is very esoteric and hard to troubleshoot.

Thanks

**Comment by mglantz** [comment]
It seems to me that this one thing is a bit messy, it is possible to make this dynamic, so that it will point at the repo from which the things are fired off from?

**Comment by haroldwongms** [comment]
This has been fixed in the latest updates.
