### ISSUE TITLE
docker cannot be started due to the OPTION configuration

### ISSUE THREAD

**Issue by zhushendhh** [Microsoft/openshift-container-platform#151]
I am trying to install OCP3.11 with this scripts and during the step 1 it shows the docker daemon cannot be started on Masters and Nodes.

I guess it may be related to: (in masterPrep.sh and nodePrep.sh)

# Update docker storage
echo "
# Adding insecure-registry option required by OpenShift
OPTIONS=\"\$OPTIONS --insecure-registry 172.30.0.0/16\"
" >> /etc/sysconfig/docker

Where is the $OPTIONS comes from ? I cannot find any var linked to this, and if it directly add "$OPTION" into /etc/sysconfig/docker, it do cannot be started.

So could you help with this ? Thank you.

**Comment by haroldwongms** [comment]
This is fine during the prep stage.  Once the deployment starts, the installer will take the --insecure-registry setting and incorporate into a brand new version of the file that will work just fine.

**Comment by haroldwongms** [comment]
Fixes now merged into master. Please try again and let me know if you still have issues.

**Comment by haroldwongms** [comment]
Assuming this is fixed since no response provided.
