### ISSUE TITLE
Openshift role out by Ansible fails

### ISSUE THREAD

**Issue by Borrelworst** [Microsoft/openshift-container-platform#156]
**Describe the bug**
OpenShift Container Platform Deployment using Ansible can never work.

**To Reproduce**
1. Deploy the platform according to the documentation
2. Results in error: The error was: 'master_publicip_fqdn' is undefined

**Expected behavior**
A deployed cluster using Ansible

**Additional context**
The problem here is that in the playbook a new play is started on the Bastion host, while all variables were set on localhost. Hence the deployment fails as the Bastion is not aware of all the facts that were set on localhost. This should be easy to fix by referencing all facts that were set in de play before as follows:

{{ hostvars['localhost']['fact'] }}

It looks like this playbook has not been tested, as it could have never worked.

**Comment by Borrelworst** [comment]
After solving this part of the playbook, it turns out that this playbook stops after deploying the infra: The installation of the Openshift container platform is never initiated. I guess that this still is Work in Progress, and it would be kind to add this to the documentation.

**Comment by haroldwongms** [comment]
Sorry for the delay.  I have been working on making a major update to the templates and scripts.  I have already incorporated the fix from @geda10 into the latest version of the templates and have opened a PR with a major revision.  Once this gets reviewed and we merge, all should be good.

**Comment by haroldwongms** [comment]
Fixes now merged into master. Please try again and let me know if you still have issues.

**Comment by haroldwongms** [comment]
Assuming this is fixed since no response provided.
