### ISSUE TITLE
OpenShift 3.10 deployment fails since Feb 25

### ISSUE THREAD

**Issue by amitlib** [Microsoft/openshift-container-platform#158]
**Describe the bug**
We deploy our OpenShift 3.10 cluster using Azure CLI with ARM. Since Feb 25 the deployment is failing with following error:
`
:57:43              "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=2\\n[stdout]\\n******************************************\\n\\nTASK [Fail when nodeName is wrong] *********************************************\\n\\nPLAY [Initialize etcd host variables] ******************************************\\n\\nTASK [Gathering Facts] *********************************************************\\nok: [ocp2166-master-0]\\n\\nTASK [set_fact] ****************************************************************\\nok: [ocp2166-master-0]\\n\\nTASK [set_fact] ****************************************************************\\nok: [ocp2166-master-0]\\n\\nPLAY [Determine openshift_version to configure on first master] ****************\\n\\nTASK [Gathering Facts] *********************************************************\\nok: [ocp2166-master-0]\\n\\nTASK [include_role] ************************************************************\\n\\nTASK [openshift_version : Use openshift_current_version fact as version to configure if already installed] ***\\n\\nTASK [openshift_version : Set openshift_version to openshift_release if undefined] ***\\nok: [ocp2166-master-0]\\n\\nTASK [openshift_version : debug] ***********************************************\\nok: [ocp2166-master-0] => {\\n    \\\"msg\\\": \\\"openshift_pkg_version was not defined. Falling back to -3.10\\\"\\n}\\n\\nTASK [openshift_version : set_fact] ********************************************\\nok: [ocp2166-master-0]\\n\\nTASK [openshift_version : debug] ***********************************************\\nok: [ocp2166-master-0] => {\\n    \\\"msg\\\": \\\"openshift_image_tag was not defined. Falling back to v3.10\\\"\\n}\\n\\nTASK [openshift_version : set_fact] ********************************************\\nok: [ocp2166-master-0]\\n\\nTASK [openshift_version : assert openshift_release in openshift_image_tag] *****\\nok: [ocp2166-master-0] => {\\n    \\\"changed\\\": false, \\n    \\\"msg\\\": \\\"All assertions passed\\\"\\n}\\n\\nTASK [openshift_version : assert openshift_release in openshift_pkg_version] ***\\nok: [ocp2166-master-0] => {\\n    \\\"changed\\\": false, \\n    \\\"msg\\\": \\\"All assertions passed\\\"\\n}\\n\\nTASK [openshift_version : debug] ***********************************************\\nok: [ocp2166-master-0] => {\\n    \\\"openshift_release\\\": \\\"3.10\\\"\\n}\\n\\nTASK [openshift_version : debug] ***********************************************\\nok: [ocp2166-master-0] => {\\n    \\\"openshift_image_tag\\\": \\\"v3.10\\\"\\n}\\n\\nTASK [openshift_version : debug] ***********************************************\\nok: [ocp2166-master-0] => {\\n    \\\"openshift_pkg_version\\\": \\\"-3.10*\\\"\\n}\\n\\nTASK [openshift_version : debug] ***********************************************\\nok: [ocp2166-master-0] => {\\n    \\\"openshift_version\\\": \\\"3.10\\\"\\n}\\n\\nTASK [set openshift_version booleans (first master)] ***************************\\nok: [ocp2166-master-0]\\n\\nPLAY [Set openshift_version for etcd, node, and master hosts] ******************\\n\\nTASK [Gathering Facts] *********************************************************\\nok: [ocp2166-infra-0]\\nok: [ocp2166-node-0]\\n\\nTASK [set_fact] ****************************************************************\\nok: [ocp2166-infra-0]\\nok: [ocp2166-node-0]\\n\\nTASK [set openshift_version booleans (masters and nodes)] **********************\\nok: [ocp2166-infra-0]\\nok: [ocp2166-node-0]\\n\\nPLAY [Verify Requirements] *****************************************************\\n\\nTASK [Gathering Facts] *********************************************************\\nok: [ocp2166-master-0]\\n\\nTASK [Run variable sanity checks] **********************************************\\nfatal: [ocp2166-master-0]: FAILED! => {\\\"msg\\\": \\\"last_checked_host: ocp2166-master-0, last_checked_var: openshift_master_manage_htpasswd;Found removed variables: openshift_hostname is replaced by Removed: See documentation; \\\"}\\n\\nPLAY RECAP *********************************************************************\\nlocalhost                  : ok=11   changed=0    unreachable=0    failed=0   \\nocp2166-infra-0            : ok=35   changed=7    unreachable=0    failed=0   \\nocp2166-master-0           : ok=54   changed=7    unreachable=0    failed=1   \\nocp2166-node-0             : ok=35   changed=7    unreachable=0    failed=0   \\n\\n\\nINSTALLER STATUS ***************************************************************\\nInitialization  : In Progress (0:03:19)\\n\\n[stderr]\\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\\n                                 Dload  Upload   Total   Spent    Left  Speed\\n\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r100    10  100    10    0     0   1117      0 --:--:-- --:--:-- --:--:--  1250\\nWARNING: The installed extension 'storage-preview' is in preview.\\nWARNING: The behavior of this command has been altered by the following extension: storage-preview\\nWARNING: The behavior of this command has been altered by the following extension: storage-preview\\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\\n                                 Dload  Upload   Total   Spent    Left  Speed\\n\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r  0 65700    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\\n                                 Dload  Upload   Total   Spent    Left  Speed\\n\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r100 65700  100 65700    0     0   335k      0 --:--:-- --:--:-- --:--:--  337k\\nWARNING: uploading /tmp/customlogo.css\\n\\rAlive[################################################################]  100.0000%\\rFinished[#############################################################]  100.0000%\\nWARNING: uploading /tmp/customlogo.png\\n\\rAlive[################################################################]  100.0000%\\rFinished[#############################################################]  100.0000%\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config\\n [WARNING]: Consider using the yum, dnf or zypper module rather than running\\nrpm.  If you need to use command because yum, dnf or zypper is insufficient you\\ncan add warn=False to this command task or set command_warnings=False in\\nansible.cfg to get rid of this message.\\n [WARNING]: Could not create retry file '/usr/share/ansible/openshift-\\nansible/playbooks/prerequisites.retry'.         [Errno 13] Permission denied:\\nu'/usr/share/ansible/openshift-ansible/playbooks/prerequisites.retry'\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"`

**To Reproduce**
Deploy cluster with following command:

az group deployment create -g <resource group> --name <name> --template-uri https://raw.githubusercontent.com/Microsoft/openshift-container-platform/release-3.10/azuredeploy.json  --parameters @./parameters.json

**Parameters file**
[parameters.txt](https://github.com/Microsoft/openshift-container-platform/files/2914072/parameters.txt)

**Expected behavior**
Cluster will be deployed

**stdout**

```
TASK [openshift_version : assert openshift_release in openshift_pkg_version] ***
ok: [ocp2175-master-0] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [openshift_version : debug] ***********************************************
ok: [ocp2175-master-0] => {
    "openshift_release": "3.10"
}

TASK [openshift_version : debug] ***********************************************
ok: [ocp2175-master-0] => {
    "openshift_image_tag": "v3.10"
}

TASK [openshift_version : debug] ***********************************************
ok: [ocp2175-master-0] => {
    "openshift_pkg_version": "-3.10*"
}

TASK [openshift_version : debug] ***********************************************
ok: [ocp2175-master-0] => {
    "openshift_version": "3.10"
}

TASK [set openshift_version booleans (first master)] ***************************
ok: [ocp2175-master-0]

PLAY [Set openshift_version for etcd, node, and master hosts] ******************

TASK [Gathering Facts] *********************************************************
ok: [ocp2175-infra-0]
ok: [ocp2175-node-0]

TASK [set_fact] ****************************************************************
ok: [ocp2175-infra-0]
ok: [ocp2175-node-0]

TASK [set openshift_version booleans (masters and nodes)] **********************
ok: [ocp2175-infra-0]
ok: [ocp2175-node-0]

PLAY [Verify Requirements] *****************************************************

TASK [Gathering Facts] *********************************************************
ok: [ocp2175-master-0]

TASK [Run variable sanity checks] **********************************************
fatal: [ocp2175-master-0]: FAILED! => {"msg": "last_checked_host: ocp2175-master-0, last_checked_var: openshift_master_manage_htpasswd;Found removed variables: openshift_hostname is replaced by Removed: See documentation; "}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=0
ocp2175-infra-0            : ok=35   changed=7    unreachable=0    failed=0
ocp2175-master-0           : ok=54   changed=7    unreachable=0    failed=1
ocp2175-node-0             : ok=35   changed=7    unreachable=0    failed=0

```

**Template Information (please complete the following information):**
 - OS: image from defaultgallery
 - Branch: 3.10

**Comment by amitlib** [comment]
Another note is that were no changes in our deployment script. 
In the bastion I can see that  under /var/lib/waagent/custom-script/donwload/0:

```
2019-02-28 08:46:57 (45.4 MB/s) - ‘updateansiblecfg.yaml’ saved [338/338]

 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'
```

**Comment by haroldwongms** [comment]
Sorry for the delay.  I have been working on making a major update to the templates and scripts.  I have already incorporated the fix from @geda10 into the latest version of the templates and have opened a PR with a major revision.  Once this gets reviewed and we merge, all should be good.

**Comment by haroldwongms** [comment]
Fixes now merged into master. Please try again and let me know if you still have issues.

**Comment by haroldwongms** [comment]
Assuming this is fixed since no response provided.
