### ISSUE TITLE
3.7 support

### ISSUE THREAD

**Issue by ryannix123** [Microsoft/openshift-container-platform#16]
Before I try to deploy a new cluster, I just wanted to see if Origin 3.7 is supported with the Azure deployment scripts.

**Comment by mglantz** [comment]
Origin? OpenShift Container Platform 3.7 is now released :)

**Comment by ryannix123** [comment]
Correct. If memory serves, when Origin 3.6 was released @haroldwongms and @BorisB2015 had to make some tweaks in the deployment scripts first.

**Comment by mglantz** [comment]
I think you mean OCP (OpenShift Container Platform). Origin is the upstream project, but this is using the downstream project from us, which is called OpenShift Container Platform :) 

Anyways, I'm testing my Azure automation for 3.7. I'll make a pull request with any changes required here.

**Comment by ryannix123** [comment]
Sorry! I should have posted my question in the Origin repo, not the OCP repo. Right now we're still testing OpenShift so we're trying to run the latest version of Origin on Azure while minimizing costs.

**Comment by haroldwongms** [comment]
I just updated OCP to 3.7.  I will work on updating Origin to 3.7 as well.
