### ISSUE TITLE
Using nipio hangs during DNS resolution check

### ISSUE THREAD

**Issue by GreenCee** [Microsoft/openshift-container-platform#169]
**Describe the bug**
Believe this is related or duplicated by: #166 
When deploying the deployment will timeout waiting for the DNS hostname resolution check. It appears this was identified in #166. Testing the PR #167 did not skip the DNS hostname resolution check though.

**To Reproduce**
1. Deploy a template on Azure Government following instructions from README.md

The Openshift installation will fail at the DNS hostname resolution task at https://github.com/Microsoft/openshift-container-platform/blob/master/scripts/deployOpenShift.sh#L224

**Expected behavior**

**Screenshots**

**stdout**
Tue Apr 23 13:27:45 UTC 2019  - Enabling HA mode for masters
Tue Apr 23 13:27:45 UTC 2019  - Create Ansible Hosts file
Tue Apr 23 13:27:45 UTC 2019  - Running DNS Hostname resolution check

PLAY [all] *********************************************************************

TASK [Wait for DNS hostname resolution - will try for up to 33 minutes] ********
fatal: [cngcluster-master01]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master01:22"}
fatal: [cngcluster-infra02]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-infra02:22"}
fatal: [cngcluster-master03]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master03:22"}
fatal: [cngcluster-infra01]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-infra01:22"}
fatal: [cngcluster-master02]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master02:22"}
[root@cngcluster-bastion 1]# cat stdout
Tue Apr 23 13:27:44 UTC 2019  - Starting Script
Tue Apr 23 13:27:44 UTC 2019  - Configuring SSH ControlPath to use shorter path name
Tue Apr 23 13:27:44 UTC 2019  - Cloning Ansible playbook repository
Cloning into 'openshift-container-platform-playbooks'...
 - Retrieved playbooks successfully
Tue Apr 23 13:27:45 UTC 2019  - Create variable for routing certificate based on certificate type
Tue Apr 23 13:27:45 UTC 2019  - Create variable for master api certificate based on certificate type
Tue Apr 23 13:27:45 UTC 2019  - Create variable for master cluster address based on cluster type
Tue Apr 23 13:27:45 UTC 2019  - Creating Master nodes grouping
Tue Apr 23 13:27:45 UTC 2019  - Creating Infra nodes grouping
Tue Apr 23 13:27:45 UTC 2019  - Creating Nodes grouping
Tue Apr 23 13:27:45 UTC 2019  - Enabling HA mode for masters
Tue Apr 23 13:27:45 UTC 2019  - Create Ansible Hosts file
Tue Apr 23 13:27:45 UTC 2019  - Running DNS Hostname resolution check

PLAY [all] *********************************************************************

TASK [Wait for DNS hostname resolution - will try for up to 33 minutes] ********
fatal: [cngcluster-master01]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master01:22"}
fatal: [cngcluster-infra02]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-infra02:22"}
fatal: [cngcluster-master03]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master03:22"}
fatal: [cngcluster-infra01]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-infra01:22"}
fatal: [cngcluster-master02]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master02:22"}
[root@cngcluster-bastion 1]# cat stdout
Tue Apr 23 13:27:44 UTC 2019  - Starting Script
Tue Apr 23 13:27:44 UTC 2019  - Configuring SSH ControlPath to use shorter path name
Tue Apr 23 13:27:44 UTC 2019  - Cloning Ansible playbook repository
Cloning into 'openshift-container-platform-playbooks'...
 - Retrieved playbooks successfully
Tue Apr 23 13:27:45 UTC 2019  - Create variable for routing certificate based on certificate type
Tue Apr 23 13:27:45 UTC 2019  - Create variable for master api certificate based on certificate type
Tue Apr 23 13:27:45 UTC 2019  - Create variable for master cluster address based on cluster type
Tue Apr 23 13:27:45 UTC 2019  - Creating Master nodes grouping
Tue Apr 23 13:27:45 UTC 2019  - Creating Infra nodes grouping
Tue Apr 23 13:27:45 UTC 2019  - Creating Nodes grouping
Tue Apr 23 13:27:45 UTC 2019  - Enabling HA mode for masters
Tue Apr 23 13:27:45 UTC 2019  - Create Ansible Hosts file
Tue Apr 23 13:27:45 UTC 2019  - Running DNS Hostname resolution check

PLAY [all] *********************************************************************

TASK [Wait for DNS hostname resolution - will try for up to 33 minutes] ********
fatal: [cngcluster-master01]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master01:22"}
fatal: [cngcluster-infra02]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-infra02:22"}
fatal: [cngcluster-master03]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master03:22"}
fatal: [cngcluster-infra01]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-infra01:22"}
fatal: [cngcluster-master02]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master02:22"}
[root@cngcluster-bastion 1]# cat stdout
Tue Apr 23 13:27:44 UTC 2019  - Starting Script
Tue Apr 23 13:27:44 UTC 2019  - Configuring SSH ControlPath to use shorter path name
Tue Apr 23 13:27:44 UTC 2019  - Cloning Ansible playbook repository
Cloning into 'openshift-container-platform-playbooks'...
 - Retrieved playbooks successfully
Tue Apr 23 13:27:45 UTC 2019  - Create variable for routing certificate based on certificate type
Tue Apr 23 13:27:45 UTC 2019  - Create variable for master api certificate based on certificate type
Tue Apr 23 13:27:45 UTC 2019  - Create variable for master cluster address based on cluster type
Tue Apr 23 13:27:45 UTC 2019  - Creating Master nodes grouping
Tue Apr 23 13:27:45 UTC 2019  - Creating Infra nodes grouping
Tue Apr 23 13:27:45 UTC 2019  - Creating Nodes grouping
Tue Apr 23 13:27:45 UTC 2019  - Enabling HA mode for masters
Tue Apr 23 13:27:45 UTC 2019  - Create Ansible Hosts file
Tue Apr 23 13:27:45 UTC 2019  - Running DNS Hostname resolution check

PLAY [all] *********************************************************************

TASK [Wait for DNS hostname resolution - will try for up to 33 minutes] ********
fatal: [cngcluster-master01]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master01:22"}
fatal: [cngcluster-infra02]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-infra02:22"}
fatal: [cngcluster-master03]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master03:22"}
fatal: [cngcluster-infra01]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-infra01:22"}
fatal: [cngcluster-master02]: FAILED! => {"changed": false, "elapsed": 2000, "msg": "Timeout when waiting for cngcluster-master02:22"}

**Template Information (please complete the following information):**
 - OS: RHEL
 - Branch: master

**Additional context**
This is using OCP trial licenses and the Azure Government environment.

**Comment by haroldwongms** [comment]
DNS hostname resolution must always work before continuing to install OpenShift as the Ansible playbooks connect to each node in the cluster by hostname.  If the DNS hostname check is failing, then that means hostname resolution is not working which is a major issue and not directly associated to OpenShift. 

Are you configuring for private clusters?  Master and Infra?  If you are, then you need to make sure you have your DNS server configured correctly.

**Comment by GreenCee** [comment]
Hi Harold, thanks for replying so quickly.
So it should be a public cluster, and using Azure DNS. So pretty vanilla install overall.
It does look like DNS was created for bastion, master and infra at least in the portal
masterdns3eqnwek4of7z2.usgovvirginia.cloudapp.usgovcloudapi.net
I'm not up to speed on Azure DNS, so I need to explore that more to grok what's happening.

Here's the parameters for a sanity check (minus rhsm info). I don't think any of these should've flipped it to a cluster. Anything obvious jump out?
I didn't edit the contoso placeholders as I interpreted they are ignored in a public cluster
{
	"$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"_artifactsLocation": {
			"value": "https://raw.githubusercontent.com/Microsoft/openshift-container-platform/master"
		},
		"masterVmSize": {
			"value": "Standard_E2s_v3"
		},
		"infraVmSize": {
			"value": "Standard_D4s_v3"
		},
		"nodeVmSize": {
			"value": "Standard_D4s_v3"
		},
		"cnsVmSize": {
			"value": "Standard_E4s_v3"
		},
		"osImageType": {
			"value": "defaultgallery"
		},
		"marketplaceOsImage": {
			"value": {
				"publisher": "RedHat",
				"offer": "RHEL",
				"sku": "7-RAW",
				"version": "latest"
			}
		},
		"storageKind": {
			"value": "managed"
		},
		"openshiftClusterPrefix": {
			"value": "cngcluster"
		},
		"minorVersion": {
			"value": "69"
		},
		"masterInstanceCount": {
			"value": 3
		},
		"infraInstanceCount": {
			"value": 3
		},
		"nodeInstanceCount": {
			"value": 3
		},
		"cnsInstanceCount": {
			"value": 3
		},
		"dataDiskSize": {
			"value": 128
		},
		"cnsGlusterDiskSize": {
			"value": 128
		},
		"adminUsername": {
			"value": "ocpadmin"
		},
		"enableMetrics": {
			"value": "true"
		},
		"enableLogging": {
			"value": "true"
		},
		"enableCNS": {
			"value": "false"
		},
		"domainName": {
			"value": "contoso.com"
		},
		"masterClusterDnsType": {
			"value": "default"
		},
		"masterClusterDns": {
			"value": "console.contoso.com"
		},
		"routingSubDomainType": {
			"value": "nipio"
		},
		"routingSubDomain": {
			"value": "apps.contoso.com"
		},
		"virtualNetworkNewOrExisting": {
			"value": "new"
		},
		"virtualNetworkName": {
			"value": "cng_openshift"
		},
		"addressPrefixes": {
			"value": "10.0.0.0/14"
		},
		"masterSubnetName": {
			"value": "cngmastersubnet"
		},
		"masterSubnetPrefix": {
			"value": "10.1.0.0/16"
		},
		"infraSubnetName": {
			"value": "cngsubnet"
		},
		"infraSubnetPrefix": {
			"value": "10.2.0.0/16"
		},
		"nodeSubnetName": {
			"value": "cngnodesubnet"
		},
		"nodeSubnetPrefix": {
			"value": "10.3.0.0/16"
		},
		"existingMasterSubnetReference": {
			"value": "/subscriptions/abc686f6-963b-4e64-bff4-99dc369ab1cd/resourceGroups/vnetresourcegroup/providers/Microsoft.Network/virtualNetworks/openshiftvnet/subnets/mastersubnet"
		},
		"existingInfraSubnetReference": {
			"value": "/subscriptions/abc686f6-963b-4e64-bff4-99dc369ab1cd/resourceGroups/vnetresourcegroup/providers/Microsoft.Network/virtualNetworks/openshiftvnet/subnets/infrasubnet"
		},
		"existingCnsSubnetReference": {
			"value": "/subscriptions/abc686f6-963b-4e64-bff4-99dc369ab1cd/resourceGroups/vnetresourcegroup/providers/Microsoft.Network/virtualNetworks/openshiftvnet/subnets/cnssubnet"
		},
		"existingNodeSubnetReference": {
			"value": "/subscriptions/abc686f6-963b-4e64-bff4-99dc369ab1cd/resourceGroups/vnetresourcegroup/providers/Microsoft.Network/virtualNetworks/openshiftvnet/subnets/nodesubnet"
		},
		"masterClusterType": {
			"value": "public"
		},
		"masterPrivateClusterIp": {
			"value": "10.1.0.200"
		},
		"routerClusterType": {
			"value": "public"
		},
		"routerPrivateClusterIp": {
			"value": "10.2.0.200"
		},
		"routingCertType": {
			"value": "selfsigned"
		},
		"masterCertType": {
			"value": "selfsigned"
		}
	}

**Comment by GreenCee** [comment]
Ah, I found the issue after some careful rereading and testing, the parameter has a placeholder of contoso.com
'"domainName": {
"value": "contoso.com"
}'

Per the readme it had to be this for a public (non-private cluster) install:
'"domainName": {
"value": "none"
}'

**Comment by haroldwongms** [comment]
Hmm.  I will have to make the change so the default in the template itself is "none".  I thought I had set that but so many things going on in there.  Thanks!
