### ISSUE TITLE
Unable to start service iptables (Container Platform Self-Managed)

### ISSUE THREAD

**Issue by vyunev** [microsoft/openshift-container-platform#176]
We're using [Container Platform Self-Managed](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/redhat.openshift-container-platform?tab=Overview) from Azure Marketplace. When we try to deploy solution to **West Europe** we failed with "Unable to start service iptables" error.

Still, we were able to deploy solution to **East US** region with no issue.

Any thoughts what the reason could be for such results? Why iptables couldn't start? Could it be different OS images in different regions?

Thanks!

Full error message:

"message": "{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"VMExtensionProvisioningError\\\",\\r\\n \\\"message\\\": \\\"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\\\\\"Enable failed: failed to execute command: command terminated with exit status=2\\\\n[stdout]\\\\nuster-infra02]\\\\nok: [ocpcluster-infra03]\\\\nok: [ocpcluster-node01]\\\\n\\\\nTASK [Validate openshift_kubelet_name_override when defined] *******************\\\\n\\\\nTASK [Validate openshift_ip exists on node when defined] ***********************\\\\n\\\\nPLAY [Configure os_firewall] ***************************************************\\\\n\\\\nTASK [Gathering Facts] *********************************************************\\\\nok: [ocpcluster-master01]\\\\nok: [ocpcluster-master02]\\\\nok: [ocpcluster-master03]\\\\nok: [ocpcluster-infra01]\\\\nok: [ocpcluster-infra02]\\\\nok: [ocpcluster-infra03]\\\\nok: [ocpcluster-node01]\\\\n\\\\nTASK [os_firewall : Fail - Firewalld is not supported on Atomic Host] **********\\\\n\\\\nTASK [os_firewall : Install firewalld packages] ********************************\\\\n\\\\nTASK [os_firewall : Ensure iptables services are not enabled] ******************\\\\n\\\\nTASK [os_firewall : Wait 10 seconds after disabling iptables] ******************\\\\n\\\\nTASK [os_firewall : Start and enable firewalld service] ************************\\\\n\\\\nTASK [os_firewall : need to pause here, otherwise the firewalld service starting can sometimes cause ssh to fail] ***\\\\n\\\\nTASK [os_firewall : Restart polkitd] *******************************************\\\\n\\\\nTASK [os_firewall : Wait for polkit action to have been created] ***************\\\\n\\\\nTASK [os_firewall : Ensure firewalld service is not enabled] *******************\\\\nchanged: [ocpcluster-infra03]\\\\nchanged: [ocpcluster-master02]\\\\nchanged: [ocpcluster-infra02]\\\\nchanged: [ocpcluster-master03]\\\\nchanged: [ocpcluster-infra01]\\\\nchanged: [ocpcluster-node01]\\\\nchanged: [ocpcluster-master01]\\\\n\\\\nTASK [os_firewall : Wait 10 seconds after disabling firewalld] *****************\\\\nPausing for 10 seconds\\\\n(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)\\\\r\\\\nok: [ocpcluster-master01]\\\\n\\\\nTASK [os_firewall : Install iptables packages] *********************************\\\\nok: [ocpcluster-infra03]\\\\nok: [ocpcluster-master03]\\\\nok: [ocpcluster-master02]\\\\nok: [ocpcluster-master01]\\\\nok: [ocpcluster-infra02]\\\\nok: [ocpcluster-node01]\\\\nok: [ocpcluster-infra01]\\\\n\\\\nTASK [os_firewall : Start and enable iptables service] *************************\\\\nfailed: [ocpcluster-master01 -> ocpcluster-master01] (item=ocpcluster-master01) => {\\\\\\\"changed\\\\\\\": false, \\\\\\\"item\\\\\\\": \\\\\\\"ocpcluster-master01\\\\\\\", \\\\\\\"msg\\\\\\\": \\\\\\\"**Unable to start service iptables: Job for iptables.service failed because the control process exited with error code.See \\\\\\\\\\\\\\\"systemctl status iptables.service\\\\\\\\\\\\\\\" and \\\\\\\\\\\\\\\"journalctl -xe\\\\\\\\\\\\\\\" for details.**\\\\\\\\n\\\\\\\"}\\\\nchanged: [ocpcluster-master01 -> ocpcluster-master02] => (item=ocpcluster-master02)\\\\nchanged: [ocpcluster-master01 -> ocpcluster-master03] => (item=ocpcluster-master03)\\\\nchanged: [ocpcluster-master01 -> ocpcluster-infra01] => (item=ocpcluster-infra01)\\\\nfailed: [ocpcluster-master01 -> ocpcluster-infra02] (item=ocpcluster-infra02) => {\\\\\\\"changed\\\\\\\": false, \\\\\\\"item\\\\\\\": \\\\\\\"ocpcluster-infra02\\\\\\\", \\\\\\\"msg\\\\\\\": \\\\\\\"Unable to start service iptables: Job for iptables.service failed because the control process exited with error code. See \\\\\\\\\\\\\\\"systemctl status iptables.service\\\\\\\\\\\\\\\" and \\\\\\\\\\\\\\\"journalctl -xe\\\\\\\\\\\\\\\" for details.\\\\\\\\n\\\\\\\"}\\\\nchanged: [ocpcluster-master01 -> ocpcluster-infra03] => (item=ocpcluster-infra03)\\\\nchanged: [ocpcluster-master01 -> ocpcluster-node01] => (item=ocpcluster-node01)\\\\n\\\\nNO MORE HOSTS LEFT *************************************************************\\\\n\\\\nPLAY RECAP *********************************************************************\\\\nlocalhost : ok=11 changed=0 unreachable=0 failed=0 \\\\nocpcluster-infra01 : ok=32 changed=8 unreachable=0 failed=0 \\\\nocpcluster-infra02 : ok=32 changed=8 unreachable=0 failed=0 \\\\nocpcluster-infra03 : ok=32 changed=8 unreachable=0 failed=0 \\\\nocpcluster-master01 : ok=51 changed=8 unreachable=0 failed=1 \\\\nocpcluster-master02 : ok=37 changed=8 unreachable=0 failed=0 \\\\nocpcluster-master03 : ok=37 changed=8 unreachable=0 failed=0 \\\\nocpcluster-node01 : ok=32 changed=8 unreachable=0 failed=0 \\\\n\\\\n\\\\nINSTALLER STATUS ***************************************************************\\\\nInitialization : Complete (0:03:28)\\\\n\\\\n[stderr]\\\\n % Total % Received % Xferd Average Speed Time Time Time Current\\\\n Dload Upload Total Spent Left Speed\\\\n\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\r100 10 100 10 0 0 1283 0 --:--:-- --:--:-- --:--:-- 1428\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config\\\\n [WARNING]: Consider using the yum, dnf or zypper module rather than running\\\\nrpm. If you need to use command because yum, dnf or zypper is insufficient you\\\\ncan add warn=False to this command task or set command_warnings=False in\\\\nansible.cfg to get rid of this message.\\\\n [WARNING]: Could not create retry file '/usr/share/ansible/openshift-\\\\nansible/playbooks/prerequisites.retry'. [Errno 13] Permission denied:\\\\nu'/usr/share/ansible/openshift-ansible/playbooks/prerequisites.retry'\\\\n\\\\\\\".\\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"

**Comment by vyunev** [comment]
Dear @haroldwongms, have you be able to dig into the issue?

**Comment by vyunev** [comment]
@haroldwongms ping

**Comment by vyunev** [comment]
Hi, during our tests we're managed ti set cluster in West Europe. Still no clue what was the reason of the errors. I close the issue for now.

**Comment by janegilring** [comment]
We are seeing the same thing. iptables starts when deploying to West Europe, but not Norway East.

Any idea what might cause this?
