### ISSUE TITLE
Development torwards OCP 3.7?

### ISSUE THREAD

**Issue by mglantz** [Microsoft/openshift-container-platform#18]
Hi all,

OpenShift Container Platform 3.7 is out. Should all new development then perhaps be geared against 3.7? I'm myself porting my own stuff to 3.7 now. If you like I can create a pull request based on my 3.7 findings.

**Comment by mglantz** [comment]
So far:
-Service Broker (enabled by default) requires separate storage
-openshift_metrics_hawkular_hostname only takes hostname
-Etcd needs to be run separately (requires own group), meaning restart is always done as if we're in HA mode.

**Comment by BorisB2015** [comment]
@haroldwongms is working on migration to 3.7. Thanks for the offer! Let's keep this open for updates/Qs, etc.

**Comment by ryannix123** [comment]
Excellent. It would be great to see metrics enabled by default for Origin as well. @haroldwongms

**Comment by mglantz** [comment]
@ryannix123 that is out-of-topic for this thread. You can contact me offline at sudo at redhat dot com if you want to discuss OpenShift architecture. Or have a look at: https://docs.openshift.com/container-platform/3.7/install_config/install/planning.html#environment-scenarios

**Comment by ryannix123** [comment]
Thanks, @mglantz. Will do. The only reason I was asking under this thread was because it related to a specific feature request/release with the OpenShift on Azure deployment scripts. I would love to see the option to deploy a cluster across multiple Azure regions. If it's possible, of course.

**Comment by mglantz** [comment]
Seems like masterPublicURL do not take for SSO. Kibana redirects to ocpm-0.abcdefghijklmnopqrstuvwxyz.fx.internal.cloudapp.net

**Comment by mglantz** [comment]
I created https://bugzilla.redhat.com/show_bug.cgi?id=1520689 for the SSO/masterPublicURL issue.

**Comment by dewolfs** [comment]
Is there a timeline when 3.7 will be available?

**Comment by haroldwongms** [comment]
I just pushed the update for 3.7.  Please take a look and provide any feedback.  Thank you!
