### ISSUE TITLE
Support for pulling RHEL OS image from Red Hat

### ISSUE THREAD

**Issue by janegilring** [microsoft/openshift-container-platform#186]
We have a single subscription from Red Hat which has entitlements for OpenShift AND RHEL OS, due to this we are unable to separate the 2 for having BYOS request just for the RHEL image. Just like the Microsoft-provided ARM template installs OpenShift from parameters JSON file by taking in values of PoolID, subscription ID, Activation ID and organization ID, can the template/parameters file be modified such that the RHEL OS image is pulled in from the above values instead of from these fields? Or is it possible to change the "offer" to something else so that the template starts to use above values to pull the RHEL OS image?

"marketplaceOsImage": {"value": {"publisher": "redhat", "offer": "rhel-byos", "sku": "rhel-76", "version": "latest"}

**Comment by abudavis** [comment]
I had the exact same question!

**Comment by haroldwongms** [comment]
I don't fully  understand the question and ask here.  RHEL is "included" as part of your OpenShift entitlements.  You only need to enter the information for the pool ID that has the OpenShift entitlements.

**Comment by janegilring** [comment]
That works well, and the customer now has gotten access to their pool ID information.
Before they got the information, they wanted to dynamically pull the OS image from RHEL the same way they dynamically pull their IBM Cloud Pak container images from Red Hat.
However, that does not seem to be a supported deployment method for OS'es in Azure, and there is no need for it anymore - hence I'll go ahead and close the issue.
