### ISSUE TITLE
Deployment failed on azure

### ISSUE THREAD

**Issue by mabdulmoghni** [Microsoft/openshift-container-platform#21]
Trying new deployment on azure .. with 
Enable Metrices : True
Enable Logging : True
Enable Cockbit : True
Enable Azure : True
And all other default values

Deployment failed with error : failed to start atomic-openshift-node.service on the infra-1 node.
below the error on azure side
 [mycluster-infra-1]\n\nTASK [populate /etc/azure/azure.conf] ******************************************\nchanged: [mycluster-infra-1]\n\nTASK [insert the azure disk config into the node] ******************************\nchanged: [mycluster-infra-1] => (item={u'value': [u'/etc/azure/azure.conf'], u'key': u'kubeletArguments.cloud-config'})\nchanged: [mycluster-infra-1] => (item={u'value': [u'azure'], u'key': u'kubeletArguments.cloud-provider'})\n\nTASK [delete the node so it can recreate itself] *******************************\nchanged: [mycluster-infra-1 -> mycluster-bastion]\n\nTASK [sleep to let node come back to life] *************************************\nPausing for 90 seconds\n(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)\r\nok: [mycluster-infra-1]\n\nRUNNING HANDLER [restart atomic-openshift-node] ********************************\nfatal: [mycluster-infra-1]: FAILED! => {\n    \"changed\": false, \n    \"failed\": true\n}\n\nMSG:\n\nUnable to restart service atomic-openshift-node: Job for atomic-openshift-node.service failed because the control process exited with error code. See \"systemctl status atomic-openshift-node.service\" and \"journalctl -xe\" for details.\n\n\tto retry, use: --limit @/home/ocpadmin/setup-azure-node.retry\n\nPLAY RECAP

on node infra-1 >>> #journalctl -xe  
Dec 27 13:21:40 mycluster-infra-1 atomic-openshift-node[76756]: I1227 13:21:40.505400   76756 server.go:127] Starting to listen on 0.0.0.0:10250
Dec 27 13:21:40 mycluster-infra-1 atomic-openshift-node[76756]: E1227 13:21:40.508422   76756 kubelet.go:1170] Image garbage collection failed: unable to find data for container /
Dec 27 13:21:40 mycluster-infra-1 atomic-openshift-node[76756]: I1227 13:21:40.508584   76756 kubelet_node_status.go:253] Setting node annotation to enable volume controller attach/detach
Dec 27 13:21:40 mycluster-infra-1 atomic-openshift-node[76756]: I1227 13:21:40.518859   76756 server.go:298] Adding debug handlers to kubelet server.
Dec 27 13:21:40 mycluster-infra-1 atomic-openshift-node[76756]: W1227 13:21:40.547310   76756 sdn_controller.go:38] Could not find an allocated subnet for node: mycluster-infra-1, Waiting...
Dec 27 13:21:40 mycluster-infra-1 atomic-openshift-node[76756]: W1227 13:21:40.750448   76756 sdn_controller.go:38] Could not find an allocated subnet for node: mycluster-infra-1, Waiting...
Dec 27 13:21:41 mycluster-infra-1 atomic-openshift-node[76756]: W1227 13:21:41.153590   76756 sdn_controller.go:38] Could not find an allocated subnet for node: mycluster-infra-1, Waiting...
Dec 27 13:21:41 mycluster-infra-1 atomic-openshift-node[76756]: W1227 13:21:41.956885   76756 sdn_controller.go:38] Could not find an allocated subnet for node: mycluster-infra-1, Waiting...
Dec 27 13:21:43 mycluster-infra-1 atomic-openshift-node[76756]: W1227 13:21:43.560179   76756 sdn_controller.go:38] Could not find an allocated subnet for node: mycluster-infra-1, Waiting...

**Comment by haroldwongms** [comment]
I will review the OCP 3.6 deployment and work on fixing the issues.  Stay tuned.

**Comment by glennswest** [comment]
any sucess? I'm seeing the same thing

**Comment by haroldwongms** [comment]
Am working on this right now.   Look for an update tomorrow.

**Comment by glennswest** [comment]
im seeing failures in 3.6 if you patch.Looks like a upstream bug kubernetes is getting confused.
    On Thursday, 18 January 2018, 7:52:04 AM GMT+8, Harold Wong <notifications@github.com> wrote:  
 
 
Am working on this right now. Look for an update tomorrow.

**Comment by haroldwongms** [comment]
No responses in quite some time.  Closing this issue.
