### ISSUE TITLE
after installation, master nodes are marked schedulable 

### ISSUE THREAD

**Issue by wrichter** [Microsoft/openshift-container-platform#3]
As part of the install process, the scripts delete the node and restarts the atomic-openshift-node agent to recreate the node config: https://github.com/Microsoft/openshift-container-platform/blob/master/scripts/deployOpenShift.sh#L375

This causes master the master nodes to be marked as schedulable and containers are scheduled to run on the masters.

@ivanthelad @rschickhaus

**Comment by dwojciec** [comment]
to correct it just execute 
$ oadm manage-node <mycluster-master-0> --schedulable=false
$ oadm drain <mycluster-master-0> --force --delete-local-data --ignore-daemonsets
<mycluster-master-0> is the name of my master node.

**Comment by haroldwongms** [comment]
I am correcting this in the next release of the templates that will deploy OpenShift Container Platform 3.6.

**Comment by haroldwongms** [comment]
Master nodes are now marked as unschedulable upon successful deployment.
