### ISSUE TITLE
Hitting the following error

### ISSUE THREAD

**Issue by dwaiba** [Microsoft/openshift-container-platform#30]
While deploying via the portal with all default parameters(logging, azure cloud, metrics and tower as false)

Hitting the following error:
`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"Conflict\",\r\n \"message\": \"{\\r\\n \\\"status\\\": \\\"Failed\\\",\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n \\\"details\\\": [\\r\\n {\\r\\n \\\"code\\\": \\\"VMExtensionProvisioningError\\\",\\r\\n \\\"message\\\": \\\"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\\\\\"Enable failed: failed to execute command: command terminated with exit status=2\\\\n[stdout]\\\\ning (24 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (23 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (22 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (21 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (20 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (19 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (18 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (17 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (16 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (15 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (14 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (13 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (12 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (11 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (10 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (9 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (8 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (7 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (6 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (5 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (4 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (3 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (2 retries left).\\\\nFAILED - RETRYING: Verify that TSB is running (1 retries left).\\\\nfatal: [mycluster-master-0]: FAILED! => {\\\\\\\"attempts\\\\\\\": 120, \\\\\\\"changed\\\\\\\": false, \\\\\\\"cmd\\\\\\\": [\\\\\\\"curl\\\\\\\", \\\\\\\"-k\\\\\\\", \\\\\\\"https://apiserver.openshift-template-service-broker.svc/healthz\\\\\\\"], \\\\\\\"delta\\\\\\\": \\\\\\\"0:00:01.023344\\\\\\\", \\\\\\\"end\\\\\\\": \\\\\\\"2018-02-07 10:03:31.482913\\\\\\\", \\\\\\\"msg\\\\\\\": \\\\\\\"non-zero return code\\\\\\\", \\\\\\\"rc\\\\\\\": 7, \\\\\\\"start\\\\\\\": \\\\\\\"2018-02-07 10:03:30.459569\\\\\\\", \\\\\\\"stderr\\\\\\\": \\\\\\\" % Total % Received % Xferd Average Speed Time Time Time Current\\\\\\\\n Dload Upload Total Spent Left Speed\\\\\\\\n\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\\\\\r 0 0 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0curl: (7) Failed connect to apiserver.openshift-template-service-broker.svc:443; Connection refused\\\\\\\", \\\\\\\"stderr_lines\\\\\\\": [\\\\\\\" % Total % Received % Xferd Average Speed Time Time Time Current\\\\\\\", \\\\\\\" Dload Upload Total Spent Left Speed\\\\\\\", \\\\\\\"\\\\\\\", \\\\\\\" 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\\\\", \\\\\\\" 0 0 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0curl: (7) Failed connect to apiserver.openshift-template-service-broker.svc:443; Connection refused\\\\\\\"], \\\\\\\"stdout\\\\\\\": \\\\\\\"\\\\\\\", \\\\\\\"stdout_lines\\\\\\\": []}\\\\n\\\\nPLAY RECAP *********************************************************************\\\\nlocalhost : ok=12 changed=0 unreachable=0 failed=0 \\\\nmycluster-infra-0 : ok=192 changed=64 unreachable=0 failed=0 \\\\nmycluster-infra-1 : ok=192 changed=64 unreachable=0 failed=0 \\\\nmycluster-master-0 : ok=655 changed=270 unreachable=0 failed=1 \\\\nmycluster-master-1 : ok=421 changed=153 unreachable=0 failed=0 \\\\nmycluster-master-2 : ok=421 changed=153 unreachable=0 failed=0 \\\\nmycluster-node-0 : ok=192 changed=64 unreachable=0 failed=0 \\\\nmycluster-node-1 : ok=192 changed=64 unreachable=0 failed=0 \\\\n\\\\n\\\\nINSTALLER STATUS ***************************************************************\\\\nInitialization : Complete\\\\nHealth Check : Complete\\\\netcd Install : Complete\\\\nMaster Install : Complete\\\\nMaster Additional Install : Complete\\\\nNode Install : Complete\\\\nHosted Install : Complete\\\\nService Catalog Install : In Progress\\\\n\\\\tThis phase can be restarted by running: playbooks/byo/openshift-cluster/service-catalog.yml\\\\n\\\\n\\\\n\\\\nFailure summary:\\\\n\\\\n\\\\n 1. Hosts: mycluster-master-0\\\\n Play: Service Catalog\\\\n Task: Verify that TSB is running\\\\n Message: non-zero return code\\\\n\\\\n[stderr]\\\\n % Total % Received % Xferd Average Speed Time Time Time Current\\\\n Dload Upload Total Spent Left Speed\\\\n\\\\r 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0\\\\r100 6 100 6 0 0 593 0 --:--:-- --:--:-- --:--:-- 666\\\\n[DEPRECATION WARNING]: 'include' for playbook includes. You should use \\\\n'import_playbook' instead. This feature will be removed in version 2.8. \\\\nDeprecation warnings can be disabled by setting deprecation_warnings=False in \\\\nansible.cfg.\\\\n[DEPRECATION WARNING]: 'include' for playbook includes. You should use \\\\n'import_playbook' instead. This feature will be removed in version 2.8. \\\\nDeprecation warnings can be disabled by setting deprecation_warnings=False in \\\\nansible.cfg.\\\\n[DEPRECATION WARNING]: The use of 'static' for 'include_role' has been \\\\ndeprecated. Use 'import_role' for static inclusion, or 'include_role' for \\\\ndynamic inclusion. This feature will be removed in a future release. \\\\nDeprecation warnings can be disabled by setting deprecation_warnings=False in \\\\nansible.cfg.\\\\n[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use \\\\n'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.\\\\n This feature will be removed in a future release. Deprecation warnings can be \\\\ndisabled by setting deprecation_warnings=False in ansible.cfg.\\\\n[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is\\\\n discouraged. The module documentation details page may explain more about this\\\\n rationale.. This feature will be removed in a future release. Deprecation \\\\nwarnings can be disabled by setting deprecation_warnings=False in ansible.cfg.\\\\n[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use \\\\n'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion. \\\\nThis feature will be removed in a future release. Deprecation warnings can be \\\\ndisabled by setting deprecation_warnings=False in ansible.cfg.\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_all_hosts\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config\\\\n [WARNING]: Consider using yum, dnf or zypper module rather than running rpm\\\\n [WARNING]: Consider using unarchive module rather than running tar\\\\n [WARNING]: Consider using get_url or uri module rather than running curl\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_containerized_master_nodes\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_nodes_use_flannel\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_nodes_use_calico\\\\n [WARNING]: Could not match supplied host pattern, ignoring:\\\\noo_nodes_use_contiv\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nodes_use_kuryr\\\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_nodes_use_nuage\\\\n [WARNING]: Could not match supplied host pattern, ignoring: glusterfs\\\\n [WARNING]: Could not match supplied host pattern, ignoring: glusterfs_registry\\\\n [WARNING]: Module did not set no_log for stats_password\\\\n [WARNING]: Module did not set no_log for external_host_password\\\\n [WARNING]: Could not create retry file '/usr/share/ansible/openshift-\\\\nansible/playbooks/byo/config.retry'. [Errno 13] Permission denied:\\\\nu'/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry'\\\\n\\\\\\\".\\\"\\r\\n }\\r\\n ]\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"}]}`

**Comment by carct** [comment]
try with different branch, believe that the master is a bit behind and that some people are working on it

https://github.com/Microsoft/openshift-container-platform/tree/release-3.6

worked just fine about a week ago, i`m going to try it again now as well

**Comment by novacain1** [comment]
This is more than likely the template service broker by default expecting the default region selector to be region=infra, which is not the case with the templates here in this repo.  I'll open a PR.

**Comment by haroldwongms** [comment]
The Master branch and Release-3.7 branch should now be updated with fixes.  Please confirm.  Thank you.

**Comment by dwaiba** [comment]
commit 77b073ecc995eb3d7d25b083864eaadaaa2c0d0f fixes this. closing

**Comment by dwaiba** [comment]
Reopening as master is consistently hitting  error
az command
`az group create -l eastus -n openshiftclusterrg && az group deployment create -g openshiftclusterrg -n openshiftcluster --template-uri https://raw.githubusercontent.com/microsoft/openshift-container-platform/master/azuredeploy.json --parameters "{\"openshiftPassword\":{\"value\":\"<password value>\"},\"enableMetrics\":{\"value\":\"true\"},\"keyVaultResourceGroup\":{\"value\":\"openshiftkvrg\"},\"sshPublicKey\":{\"value\":\"<ssh-publickey-value>"},\"enableCockpit\":{\"value\":\"true\"},\"rhsmUsernameOrOrgId\":{\"value\":\"<rhsm username>\"},\"rhsmPasswordOrActivationKey\":{\"value\":\"<rhsm password>\"},\"rhsmPoolId\":{\"value\":\"<pool id>\"},\"keyVaultName\":{\"value\":\"openshiftprivkeys\"},\"keyVaultSecret\":{\"value\":\"openshiftprivkeys\"},\"aadClientId\":{\"value\":\"<client_id>\"},\"aadClientSecret\":{\"value\":\"<client_secret>\"}}" --debug`

Error:
`Deployment failed. Correlation ID: 56e8c7b4-79fa-4cff-b5c7-5b0bda7e00a2. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'deployOpenShift'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=2\\n[stdout]\\n\\\"python-httplib2\\\", \\\"yum-utils\\\"]}}}, \\\"package_version\\\": {\\\"failed\\\": true, \\\"failures\\\": [[\\\"OpenShiftCheckException\\\", \\\"Some required package(s) are available at a version\\\\nthat is higher than requested\\\\n  docker-1.13.1\\\\nThis will prevent installing the version you requested.\\\\nPlease check your enabled repositories or adjust openshift_release.\\\"]], \\\"invocation\\\": {\\\"module_args\\\": {\\\"package_list\\\": [{\\\"check_multi\\\": false, \\\"name\\\": \\\"openvswitch\\\", \\\"version\\\": [\\\"2.6\\\", \\\"2.7\\\", \\\"2.8\\\"]}, {\\\"check_multi\\\": false, \\\"name\\\": \\\"docker\\\", \\\"version\\\": \\\"1.12\\\"}, {\\\"check_multi\\\": true, \\\"name\\\": \\\"atomic-openshift\\\", \\\"version\\\": \\\"3.7\\\"}, {\\\"check_multi\\\": true, \\\"name\\\": \\\"atomic-openshift-master\\\", \\\"version\\\": \\\"3.7\\\"}, {\\\"check_multi\\\": true, \\\"name\\\": \\\"atomic-openshift-node\\\", \\\"version\\\": \\\"3.7\\\"}], \\\"package_mgr\\\": \\\"yum\\\"}}, \\\"last_failed\\\": {\\\"failed\\\": true, \\\"invocation\\\": {\\\"module_args\\\": {\\\"package_list\\\": [{\\\"check_multi\\\": false, \\\"name\\\": \\\"openvswitch\\\", \\\"version\\\": [\\\"2.6\\\", \\\"2.7\\\", \\\"2.8\\\"]}, {\\\"check_multi\\\": false, \\\"name\\\": \\\"docker\\\", \\\"version\\\": \\\"1.12\\\"}, {\\\"check_multi\\\": true, \\\"name\\\": \\\"atomic-openshift\\\", \\\"version\\\": \\\"3.7\\\"}, {\\\"check_multi\\\": true, \\\"name\\\": \\\"atomic-openshift-master\\\", \\\"version\\\": \\\"3.7\\\"}, {\\\"check_multi\\\": true, \\\"name\\\": \\\"atomic-openshift-node\\\", \\\"version\\\": \\\"3.7\\\"}], \\\"package_mgr\\\": \\\"yum\\\"}}, \\\"msg\\\": \\\"Some required package(s) are available at a version\\\\nthat is higher than requested\\\\n  docker-1.13.1\\\\nThis will prevent installing the version you requested.\\\\nPlease check your enabled repositories or adjust openshift_release.\\\"}, \\\"msg\\\": \\\"Some required package(s) are available at a version\\\\nthat is higher than requested\\\\n  docker-1.13.1\\\\nThis will prevent installing the version you requested.\\\\nPlease check your enabled repositories or adjust openshift_release.\\\"}}, \\\"msg\\\": \\\"One or more checks failed\\\", \\\"playbook_context\\\": \\\"install\\\"}\\n\\nNO MORE HOSTS LEFT *************************************************************\\n\\nPLAY RECAP *********************************************************************\\nlocalhost                  : ok=11   changed=0    unreachable=0    failed=0   \\nmycluster-infra-0          : ok=45   changed=4    unreachable=0    failed=1   \\nmycluster-infra-1          : ok=45   changed=4    unreachable=0    failed=1   \\nmycluster-master-0         : ok=47   changed=4    unreachable=0    failed=1   \\nmycluster-master-1         : ok=46   changed=4    unreachable=0    failed=1   \\nmycluster-master-2         : ok=46   changed=4    unreachable=0    failed=1   \\nmycluster-node-0           : ok=45   changed=4    unreachable=0    failed=1   \\nmycluster-node-1           : ok=45   changed=4    unreachable=0    failed=1   \\n\\n\\nINSTALLER STATUS ***************************************************************\\nInitialization            : Complete\\nHealth Check               : In Progress\\n\\tThis phase can be restarted by running: playbooks/byo/openshift-checks/pre-install.yml\\n\\n\\n\\nFailure summary:\\n\\n\\n  1. Hosts:    mycluster-infra-0, mycluster-infra-1, mycluster-master-0, mycluster-master-1, mycluster-master-2, mycluster-node-0, mycluster-node-1\\n     Play:     OpenShift Health Checks\\n     Task:     Run health checks (install) - EL\\n     Message:  One or more checks failed\\n     Details:  check \\\"package_version\\\":\\n               Some required package(s) are available at a version\\n               that is higher than requested\\n                 docker-1.13.1\\n               Thiswill prevent installing the version you requested.\\n               Please check your enabled repositories or adjust openshift_release.\\n\\nThe execution of \\\"/usr/share/ansible/openshift-ansible/playbooks/byo/config.yml\\\" includes checks designed to fail early if the requirements of the playbook are not met. One or more of these checks failed. To disregard these results,explicitly disable checks by setting an Ansible variable:\\n   openshift_disable_check=package_version\\nFailing check names are shown in the failure details above. Some checksmay be configurable by variables if your requirements are different from the defaults; consult check documentation.\\nVariables can be setin the inventory or passed on the command line using the -e flag to ansible-playbook.\\n\\n[stderr]\\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\\n                                 Dload  Upload   Total   Spent    Left  Speed\\n\\r  0     0  0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r100     6  100     6    0     0    550      0 --:--:-- --:--:-- --:--:--   600\\n[DEPRECATION WARNING]: 'include' for playbook includes. You should use \\n'import_playbook' instead. This feature will be removed in version 2.8. \\nDeprecation warnings can be disabled by setting deprecation_warnings=False in \\nansible.cfg.\\n[DEPRECATION WARNING]: 'include' for playbook includes. You should use \\n'import_playbook' instead. This feature will be removed in version 2.8. \\nDeprecation warnings can be disabled by setting deprecation_warnings=False in \\nansible.cfg.\\n[DEPRECATION WARNING]: The use of 'static' for 'include_role' has been \\ndeprecated. Use 'import_role' for static inclusion, or 'include_role' for \\ndynamic inclusion. This feature will be removed in a future release. \\nDeprecation warnings can be disabled by setting deprecation_warnings=False in \\nansible.cfg.\\n[DEPRECATIONWARNING]: The use of 'include' for tasks has been deprecated. Use \\n'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.\\n This feature will be removed in a future release. Deprecation warnings can be \\ndisabled by setting deprecation_warnings=False in ansible.cfg.\\n[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is\\n discouraged. The module documentation details page may explain more about this\\n rationale.. This feature will be removed in a future release. Deprecation \\nwarnings can bedisabled by setting deprecation_warnings=False in ansible.cfg.\\n[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use \\n'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion. \\nThis feature will be removed in a future release. Deprecation warnings can be \\ndisabled by setting deprecation_warnings=False in ansible.cfg.\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_all_hosts\\n [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config\\n [WARNING]: Could not match suppliedhost pattern, ignoring: oo_nfs_to_config\\n [WARNING]: Could not create retry file '/usr/share/ansible/openshift-\\nansible/playbooks/byo/config.retry'.         [Errno 13] Permission denied:\\nu'/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry'\\n\\\".\"\r\n }\r\n    ]\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}`

**Comment by dwaiba** [comment]
Duplicate of #48 and PR #53 created for fixing all with cross references
