### ISSUE TITLE
after installation, the node tags are missing - causes fluentd deployment not to take place

### ISSUE THREAD

**Issue by wrichter** [Microsoft/openshift-container-platform#4]
As part of the install process, the scripts delete the node and restarts the atomic-openshift-node agent to recreate the node config: https://github.com/Microsoft/openshift-container-platform/blob/master/scripts/deployOpenShift.sh#L375

this causes all tags - especially "logging-infra-fluentd: 'true'" to go missing, hence fluentd is not deployed.

Repair: just label all nodes again with logging-infra-fluentd: 'true'

oc label nodes --all logging-infra-fluentd=true

@ivanthelad @rschickhaus

**Comment by haroldwongms** [comment]
I am fixing this in the next release of the templates that will deploy OpenShift Container Platform 3.6.

**Comment by haroldwongms** [comment]
logging-Infra-fluentd=true and logging=true labels set as part of setup.
