### ISSUE TITLE
Request from customer on changing the port from default 8443 to 443. 

### ISSUE THREAD

**Issue by piggyvenus** [Microsoft/openshift-container-platform#44]
Given than the router is running on a different host from the master(s). It would be nice if there is an option to change the Web UI port number by providing the following parameter in the inventory file. 
## In this cluster 443 is used by router, so we cannot use 443 for master
openshift_master_api_port=443
openshift_master_console_port=443
Thanks!

**Comment by haroldwongms** [comment]
OCP 3.9 in master and release-3.9 branch as well as the azurestack-release-3.7 and azurestack-release-3.9 branches are now using port 443.  Do we need to port this to release-3.7 and release3-6 as well?

**Comment by haroldwongms** [comment]
Have not heard back but since we have now changed to using port 443 in 3.9, I am closing.
