### ISSUE TITLE
azuredeploy.json only provide one RHSM PoolId but mine subscription has two

### ISSUE THREAD

**Issue by meeuwesen** [Microsoft/openshift-container-platform#46]
I have to PoolId's both are RH Openshift Enterprise. 
One is the "Red Hat OpenShift Container Platform Broker/Master Infrastructure" and the other is
"Red Hat OpenShift Container Platform, Standard, 2-Core".
I doesn't matter which one i use, in the error logging it state 
"Incorrect Pool ID or no entitlements available"
I want 9 system connect to the 2-core subscription and the others to the infrastructure subscription.
Hope you can help

**Comment by meeuwesen** [comment]
selecting the infrastructure poolid from the two went wel with the release-3.7.
now testing against the release-3.6 branch

**Comment by haroldwongms** [comment]
@meeuwesen The licensing does give you "extra" so you can install masters and infra nodes since those do not get charged for but must be attached to pool in order to get rpms.  Please update with your status.  Thanks.

**Comment by haroldwongms** [comment]
The 3.10 branch supports broker pool id for use by bastion, masters, and infra nodes.
