### ISSUE TITLE
Cluster DNS not configured properly?

### ISSUE THREAD

**Issue by heatmiser** [Microsoft/openshift-container-platform#5]
Deployed 3x3x3 master/infra/node configuration.  Can login and deploy basic pod apps, however, deploying things like example CI/CD pipelines w/ Jenkins integration...
https://raw.githubusercontent.com/kenthua/nodejs-ex/demo/bluegreen-pipeline.yml
...fails to work properly.  Build pipeline does not work. Looking at the log for the Jenkins pod, it's unable to reach openshift.default.svc. Issue seems to point to cluster DNS? Or is there some other basic configuration that is missing that I need to complete post deployment of the ARM template to Azure?
Saw similar behavior when trying to deploy this CoolStore demo: https://github.com/alezzandro/coolstore-microservice
The components of the demo can not deploy correctly, because once started, none of the builds can lookup the nexus svc.

Here is kubernetes/DNS configuration on OpenShift 3.5 on Azure:
oc get service kubernetes -n default -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-09-25T05:36:27Z
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "170"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: 79c495ad-a1b3-11e7-ba76-000d3a931eae
spec:
  clusterIP: 172.30.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  sessionAffinity: ClientIP
  type: ClusterIP
status:
  loadBalancer: {}

[user@host]$ oc project huatest1
Already on project "huatest1" on server "https://obfuscated-mstr01.region.cloudapp.azure.com:8443".
[user@host]$ oc get pods
NAME              READY     STATUS    RESTARTS   AGE
jenkins-1-xkj7h   1/1       Running   0          2h
mongodb-1-s01pz   1/1       Running   0          2h
[user@host]$ oc rsh jenkins-1-xkj7h
sh-4.2$ curl openshift.default.svc:443
curl: (6) Could not resolve host: openshift.default.svc; Name or service not known
sh-4.2$ exit
exit

Compared to kubernetes/DNS configuration on OpenShift CDK running minishift locally...

oc get service kubernetes -n default -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-09-15T22:01:01Z
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "620"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: 5c877e73-9a61-11e7-96f8-525400ab5a26
spec:
  clusterIP: 172.30.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 8053
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 8053
  sessionAffinity: ClientIP
  type: ClusterIP
status:
  loadBalancer: {}

 [user@host]$ oc project huatest1
Now using project "huatest1" on server "https://192.168.42.205:8443".
 [user@host]$ oc get pods
NAME                                   READY     STATUS      RESTARTS   AGE
jenkins-1-pqzxr                        1/1       Running     1          1h
mongodb-1-8q3z7                        1/1       Running     1          1h
nodejs-mongodb-example-1-build         0/1       Completed   0          1h
nodejs-mongodb-example-green-1-tkqm9   1/1       Running     1          1h
  [user@host]$ oc rsh jenkins-1-pqzxr
sh-4.2$ curl openshift.default.svc:443

sh-4.2$ exit
exit

**Comment by shavlikleague** [comment]
Setting openshift_use_dnsmasq=true for each occurrence in scripts/deployOpenShift.sh has resolved the issue.

**Comment by haroldwongms** [comment]
I am fixing this in the next release of the templates that will deploy OpenShift Container Platform 3.6.  In 3.6, openshift_use_dnsmasq=true is required.

**Comment by haroldwongms** [comment]
Now using dnsmasq=true.

Closing.
