### ISSUE TITLE
logging installation on 3.7 branch fails with azure cloud provider enabled

### ISSUE THREAD

**Issue by miosman** [Microsoft/openshift-container-platform#51]
When using the 3.7 branch with Azure cloud provider enabled, the installation of the logging component fails due to the PVC for elasticsearch containing spec selectors.  
`openshift_logging_storage_labels={'storage': 'logging'}`

Label selectors are not supported by azure-disk see https://github.com/kubernetes/kubernetes/issues/58413 and as such for the installation to complete the line above should be commented out. I see that it is indeed commented on master by not on the release-3.7 branch.

**Comment by vincepower** [comment]
This is already fixed on the master branch, and it is also included in PR50 for the release-3.7 branch.

Comment out, or remove, this line in deployOpenShift.sh:
`
openshift_logging_storage_labels={'storage': 'logging'}
`

**Comment by haroldwongms** [comment]
Closing this issue as it was fixed with PR #50
