### ISSUE TITLE
Some required package(s) are available at a version that is higher than requested

### ISSUE THREAD

**Issue by erjosito** [Microsoft/openshift-container-platform#56]
Hi there, 

The deployment of the master branch fails with the message "Some required package(s) are available at a version that is higher than requested docker-1.13.1".

In deployOpenshift.sh I added the flag package_version to openshift_disable_check, the line looks like this in my fork:
openshift_disable_check=memory_availability,docker_image_availability,package_version

With that the installation seems to work.

Or should I be using the branch 3.7 instead of master?

**Comment by miosman** [comment]
If you are deploying openshift 3.7 you should use 3.7 branch.  master can contain experimental things for the next release of openshift.

**Comment by RubyonSnow** [comment]
This happens also when using the 3.6 branch. Is there any workaround that doesn't require the usage of 3.7?

**Comment by miosman** [comment]
the same workaround for 3.7 branch will work for 3.6.

1. disable the package version check
`openshift_disable_check=memory_availability,docker_image_availability,package_version`

2. change masterPrep.sh and nodePrep.sh to install the correct docker version
`yum -y install docker-1.12.6`

**Comment by haroldwongms** [comment]
I didn't realize we did not update the 3.6 branch yet.  I will work on updating this over the next few days.

**Comment by RubyonSnow** [comment]
Working with branch 3.7 and basically changing version No. to 3.6 worked better than trying to fix branch 3.6 btw. :)

**Comment by haroldwongms** [comment]
@erjosito Can you please verify that you are still seeing this issue with release-3.7 or master (which is 3.9)?  We fixed the docker issue for 3.6, 3.7 and 3.9.
Thanks.

**Comment by erjosito** [comment]
I tested the 3.9 branch and it worked like a charm! Thanks!

**Comment by haroldwongms** [comment]
Closing as this issue is resolved.
