### ISSUE TITLE
Installation failed due to "Changing Availability Set SKU from 'Aligned' to 'Classic' is not allowed"

### ISSUE THREAD

**Issue by taneem-ibrahim** [Microsoft/openshift-container-platform#57]
I put "storageKind" attribute value as unmanaged and for location (-l) I put "South Central US".
```

"storageKind": {
			"value": "unmanaged"
		},
```

**Comment by haroldwongms** [comment]
The error sounds like you started with aligned (Managed) and tried to switch to classic (unmanaged).  Was this a new cluster deployment in a new resource group?

**Comment by taneem-ibrahim** [comment]
Hi Harold, 

Thank you for the reply. Yes it was a new cluster. I did not intentionally mention anything regarding managed or unmanaged in the initial set of commands. The only place where I added that attribute was in storageKind. Does the script by default create the Azure VMs with managed disks even if the template json file has "unmanaged" configured? 

I ended up creating the OpenShift cluster using unmanaged storage from scratch fine. However, I would love to know where the issue was out of curiosity. The template will save me a lot of time in the future!

Cheers,
Taneem

**Comment by haroldwongms** [comment]
@taneem-ibrahim Can you please confirm if you are still seeing this issue?  I have made some changes to the templates and have just tested the master branch with both unmanaged and managed disks.  Both configurations deploy successfully.  Thank you.

**Comment by taneem-ibrahim** [comment]
@haroldwongms It works now! Thank you so much, Harold.
