### ISSUE TITLE
bastionPrep.sh caused recent deploy to fail

### ISSUE THREAD

**Issue by heatmiser** [Microsoft/openshift-container-platform#8]
This line in ./scripts/bastionPrep.sh caused my recent deploy to fail...

yum install atomic-openshift-excluder atomic-openshift-docker-excluder

From stdout on bastion node...
atomic-openshift-excluder not found

Script line should be...
yum -y install atomic-openshift-excluder atomic-openshift-docker-excluder

**Comment by haroldwongms** [comment]
Fixed.
