### ISSUE TITLE
MySQL or MongoDB persistent template from the OCP 3.6.1 catalog non working

### ISSUE THREAD

**Issue by adibalsa** [Microsoft/openshift-container-platform#85]
Version: oc v3.6.1

I've deployed a 3.6.1 OCP cluster on Azure 2-3 weeks ago using Azure template. Deployment succeeded and cluster is up&running. I've deployed some images (like NGINX and others) and everything looks fine.
However if I deploy a MongoDB from OCP catalog (plain vanilla MongoDB) using persistent storage (PV) the deployment fails with this messagge (simlar error if I deploy MySQL or even Cassandra DB):

=> MongoDB
=> sourcing 10-check-env-vars.sh ...
--
  | => sourcing 20-setup-wiredtiger-cache.sh ...
  | => [Wed Mar 21 09:17:40] wiredTiger cacheSizeGB set to 1
  | => sourcing 30-set-config-file.sh ...
  | => sourcing 35-setup-default-datadir.sh ...
  | ERROR: Couldn't write into /var/lib/mongodb/data
  | CAUSE: current user doesn't have permissions for writing to /var/lib/mongodb/data directory
  | DETAILS: current user id = 184, user groups: 997 0
  | DETAILS: directory permissions: drwxr-xr-x owned by 0:1000360000, SELinux: system_u:object_r:svirt_sandbox_file_t:s0:c9,c19

Digging down the problem, I see that PV are successfully created on Azure Storage account and mounted to the OCP working nodes. If log to a specific node I see all mounted volumes.

**Comment by haroldwongms** [comment]
Please use a newer version of OpenShift and let us know if the issue persists.
