### ISSUE TITLE
Do Not use Premium_LRS for Docker Registry storage account

### ISSUE THREAD

**Issue by heatmiser** [Microsoft/openshift-container-platform#86]
Not sure if you have a Notes section for this project, however, I ran into the following so I thought I would make folks aware and maybe save people some time.  Ran into the following issue when I changed the Docker Registry storage account to Premium_LRS:

https://github.com/theobolo/kube-registry-azure/issues/1

When the Docker Registry storage account is set to Premium_LRS, everything will deploy fine, however, when you go to deploy an application, the build will bomb out because the Docker Registry storage account will be inaccessible.  To fix, scale the docker-registry pod to zero, delete the storage account and recreate with a different name using Standard_LRS, then create a new container under the new storage account using the same name as in the previous storage account.  Once created, copy the access key for the new storage account and in the environment settings for the docker-registry deployment, change the storage account name to the new name and paste the access key into REGISTRY_STORAGE_AZURE_ACCOUNTKEY.  Save changes and a new docker-registry pod will deploy.  Application deployments will now work correctly.

**Comment by heatmiser** [comment]
Harold, thanks for the verification. Yes, I have forked the repo, however, only to be able to modify the deploy shell scripts.  I am using Terraform to deploy all underlying infrastructure resources prior to executing prep/deploy shell scripts.

Greatly appreciate the quick response!

**Comment by haroldwongms** [comment]
Documentation will be updated to call this out.  Closing this issue.
