### ISSUE TITLE
Deployment keeps failing if system is already registered

### ISSUE THREAD

**Issue by alezzandro** [Microsoft/openshift-container-platform#98]
Hi, 

it seems that Azure deployment keeps failing also after the PR #75.

In file  

> openshift-container-platform/scripts/bastionPrep.sh 

 and the other preparation scripts:
```
subscription-manager register --username="$USERNAME_ORG" --password="$PASSWORD_ACT_KEY" || subscription-manager register --activationkey="$PASSWORD_ACT_KEY" --org="$USERNAME_ORG"

if [ $? -eq 0 ]
then
   echo "Subscribed successfully"
elif [ $? -eq 64 ]
then
           echo "This system is already registered."
else
   echo "Incorrect Username / Password or Organization ID / Activation Key specified"
   exit 3
fi
```

The "$?" value is consumed by the first IF, it should be saved in a variable to keep checking it in a IF/ELSIF construct.

I've also checked that the next IF will not match *always* the exact string (sometimes subscription-manager will output more than a string, for example while re-generating certificates):
```

subscription-manager attach --pool=$POOL_ID > attach.log
if [ $? -eq 0 ]
then
   echo "Pool attached successfully"
else
   evaluate=$( cut -f 2-5 -d ' ' attach.log )
   if [[ $evaluate == "unit has already had" ]]
      then
         echo "Pool $POOL_ID was already attached and was not attached again."
	  else
         echo "Incorrect Pool ID or no entitlements available"
         exit 4
   fi
fi
```

I'll submit a PR for fixing these issues.

Thanks.

**Comment by haroldwongms** [comment]
Closing this issue as it was fixed with multiple PRs.
